---
title: "STat 123 Lab 7"
author: "Eric Huber"
date: "16/03/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Question 1:
```{r, q1a}
### (1.a)
df = read.csv("lab7_data.csv")

### (1.b)
nums = as.matrix(df[,2:5])

### (1.c)
c3 = nums[,3]

### (1.d)
sc3 = 0 
n = length(c3)

for (i in 1:n){
  sc3 = sc3 + c3[i]
  i = i+1
}
```


## Question 2:
```{r, q2}
### (2.a)
c2 = nums[,2]
c4 = nums[,4]

### (2.b)
row_sums = rep(0, length(c2))
i = 0

### (2.c)
for(i in 1:length(c2)){
  row_sums[i] = c2[i]+c3[i]+c4[i]
  i = i+1
}

### (2.d)
row_sums
```

## Question 3:
```{r, q3}
### (3.a)
nums = cbind(nums,rep(0, length(nums[,1])))

### (3.b)
i = 1
n = length(nums[,1])

for(i in 1:n){
nums[i,5] = nums[i,1]+nums[i,2]+nums[i,3]+nums[i,4]
  i = i+1
}

### (3.c)
nums

```

## Question 4:
```{r, q4}
## (4.a)
nums = cbind(nums,rep(0, length(nums[,1])))

## (4.b)
numscopy = nums
nums[,6] = apply(nums[,1:5], 1 ,sum)

## (4.c)
nums
```

## Bonus
```{r, bonus}
## 1
nums = rbind(nums,rep(0, length(nums[1,])))

## 2
nums[13,] = apply(nums[1:12,], 2, sum)

## 3 
nums
```





