---
title: "Lab6"
author: "Eric Huber"
date: "09/03/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Question 1:

#### (1.a)
```{r, q1a}
fwd = LETTERS
```

###(1.b)
```{r, q1b}
i = 1
bkwd = numeric()
k= length(fwd)

while(i <= k){
  bkwd[i] = c(fwd[k+1-i]) 
  i = i+1
    }
```


## Question 2:


### (2.a)
```{r, q2a}
nd = read.csv(file = "normaldist.csv")


```


### (2.b)
```{r, q2b}
mu = mean(nd$x)

```


### (2.c)
```{r, q2c}
sig = sd(nd$x)
```


### (2.d)
```{r, q2d}
qnorm(.57, mu, sig)
```

## Question 3:

###(3.a)
```{r, q3a}
bb = read.csv(file = "boombust.csv") 
```

### (3.b)
```{r, q3b}
bb = na.omit(bb)
```

### (3.c)
```{r, q3c}
n = dim(bb)[1]

```

### (3.d)
```{r, q3d}
goodbad = data.frame(matrix(ncol = 2, nrow = n))
colnames(goodbad) = c("Good", "Bad")


```

###(3.e)
```{r, q3e}
j = 1

while(j<=n){
  if(bb$Boom[j] >= bb$Bust[j]){
    goodbad$Good[j] = bb$Name[j]
  }
  else{
    goodbad$Bad[j] = bb$Name[j]
  }
 
  j = j+1
}
```


### (3.f)
```{r, q3f}
length(goodbad$Good[!is.na(goodbad$Good)])

```

### (3.g)
```{r, q3g}
length(goodbad$Bad[!is.na(goodbad$Bad)])


```





