---
title: "Lab 9 - STAT 123"
author: "Eric Huber"
date: "30/03/2022"
output: word_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1:

```{r, q1}
# a
df = read.csv("media_spend.csv")

#b,c
par(mfrow = c(1,3))

cnames= c("TV Ad", "Radio Ad", "Newspaper Ad")
colours = c("dodgerblue", "firebrick1", "green3")


for(i in 1:3){
  ttl = paste("Sales vs", cnames[i])
  plot(df[,i], df[,4], main = ttl, ylab = "# of Sales", col = colours[i], xlab = cnames[i])
  
  i = i+1
  
}

```
### (1.c) 
Looking at our plots it appears that TV ads seem to be the most positively correlated having the largest affect on sales!

## Question 2:
```{r, q2}
res = numeric(3)

names(res)= c("TV", "Radio", "News")


fit_TV = lm(formula =df$Sales~df$TV)

res[1] = summary(fit_TV)$coefficients[2, 4]

res[2] = summary(lm(Sales ~ Radio, data = df))$coefficients[2,4]

res[3] = summary(lm(Sales ~ Newspaper, data = df))$coefficients[2,4]

res

```
Based on our results it's clear to see that TV is by far the most significant regressor as it has the smallest p value.






